[project]
name = "astar-island"
version = "0.1.0"
description = "Norse civilization simulator prediction for NM i AI 2026"
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "scipy",
    "requests",
    "python-dotenv",
]

[dependency-groups]
dev = [
    "numpy>=2.4.3",
    "pytest>=9.0.2",
]
